server:
  port: 8020

ecg:
  service:
    # 采购平台请购单地址
    praybill: http://192.168.1.20:8080/rest-api/receive/ncPoOrder
    # 采购平台合同地址
    ctpu: http://192.168.1.20:8080/rest-api/receive/erpContractResult
    # ERP采购合同地址
    ectpu: http://192.168.1.5:80/uapws/rest/ecgservice/creatbill
    # ERP年标计划地址
    eplan: http://192.168.1.5:80/uapws/rest/ecgservice/creatplanbill



spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://localhost:3306/ecg?serverTimezone=Hongkong&useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
        profile-enable: true  # 能够监控单个url调用的sql列表
        url-pattern: /*       # 监控路径控制  eg: /admin/*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*' # 不拦截的路径
      statViewServlet:
        enabled: true
        # java项目fhadmin.cn
        # 设置白名单，不填则允许所有访问
        allow:
        deny: 192.168.2.61                 # ip黑名单，禁止访问的地址 优先级高于白名单
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: druid
        login-password: druid
        reset-enable: true               # 是否能够重置数据
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true